[project]
name = "gkls"
version = "0.1.1"
dependencies = ["Cython==3.0.11"]

[build-system]
requires = ["setuptools", "toml", "Cython==3.0.11"]

[tool.setuptools.packages.find]
where = ["src", "include"]

[tool.setuptools.exclude-package-data]
optimizers = ["pygkls.cc"]
